/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user (set session cookie or return token) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            accessToken?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: {
            parameters: {
                query?: {
                    status?: "draft" | "planning" | "execution" | "completed" | "archived";
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            responses: {
                /** @description Project created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update project by id */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            responses: {
                /** @description Project updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List contracts */
        get: {
            parameters: {
                query?: {
                    projectId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contract list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contract"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create contract */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Contract"];
                };
            };
            responses: {
                /** @description Contract created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contract"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get contract by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contract detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contract"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/purchase-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List purchase orders for project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Purchase order list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseOrder"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create purchase order for project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PurchaseOrder"];
                };
            };
            responses: {
                /** @description Purchase order created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseOrder"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project ledger */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ledger entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            invoices?: components["schemas"]["Invoice"][];
                            payments?: components["schemas"]["Payment"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record payment for project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            responses: {
                /** @description Payment recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List progress reports for project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Progress report list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgressReport"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create progress report for project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProgressReport"];
                };
            };
            responses: {
                /** @description Progress report created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgressReport"];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get presigned upload URL */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example progress-1.jpg */
                        filename: string;
                        /** @example image/jpeg */
                        contentType: string;
                    };
                };
            };
            responses: {
                /** @description Presigned upload URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            uploadUrl?: string;
                            /** Format: uri */
                            publicUrl?: string;
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example usr_001 */
            id: string;
            /** @example Budi Santoso */
            name: string;
            /**
             * Format: email
             * @example budi@company.com
             */
            email: string;
            /**
             * @example [
             *       "project_manager"
             *     ]
             */
            roles: string[];
            attributes: {
                /**
                 * @example [
                 *       "prj_001",
                 *       "prj_002"
                 *     ]
                 */
                projectIds: string[];
                /** @example org_001 */
                orgId: string;
                /**
                 * Format: double
                 * @example 100000000
                 */
                financialLimit: number;
            };
        };
        ErrorResponse: {
            error: {
                /** @example VALIDATION_ERROR */
                code: string;
                /** @example Invalid request payload. */
                message: string;
                details?: {
                    [key: string]: unknown;
                }[];
            };
        };
        Project: {
            /** @example prj_001 */
            id: string;
            /** @example Pembangunan Gudang A */
            name: string;
            /** @example cli_001 */
            clientId: string;
            /** @enum {string} */
            status: "draft" | "planning" | "execution" | "completed" | "archived";
            /**
             * Format: double
             * @example 2500000000
             */
            budgetTotal: number;
            /**
             * Format: date
             * @example 2026-02-01
             */
            startDate: string;
            /**
             * Format: date
             * @example 2026-12-20
             */
            endDate: string;
        };
        Contract: {
            /** @example ctr_001 */
            id: string;
            /** @example prj_001 */
            projectId: string;
            /** @example sup_001 */
            contractorId: string;
            /** @example Struktur dan finishing */
            scope: string;
            /**
             * Format: date
             * @example 2026-02-10
             */
            signedAt: string;
            paymentSchedule: {
                /** @example DP 30% */
                milestone: string;
                /**
                 * Format: double
                 * @example 750000000
                 */
                amount: number;
                /**
                 * Format: date
                 * @example 2026-03-01
                 */
                dueDate: string;
            }[];
        };
        PurchaseOrderItem: {
            /** @example Besi beton 10mm */
            name: string;
            /**
             * Format: double
             * @example 100
             */
            qty: number;
            /**
             * Format: double
             * @example 120000
             */
            unitPrice: number;
            /** @example batang */
            unit?: string;
        };
        PurchaseOrder: {
            /** @example po_001 */
            id: string;
            /** @example prj_001 */
            projectId: string;
            /** @example sup_001 */
            supplierId: string;
            items: components["schemas"]["PurchaseOrderItem"][];
            /**
             * Format: double
             * @example 12000000
             */
            totalAmount: number;
            /** @enum {string} */
            status: "draft" | "issued" | "delivered" | "cancelled";
        };
        Invoice: {
            /** @example inv_001 */
            id: string;
            /** @example prj_001 */
            projectId: string;
            /** @example sup_001 */
            vendorId: string;
            /**
             * Format: double
             * @example 50000000
             */
            amount: number;
            /** @enum {string} */
            status: "unpaid" | "partial" | "paid" | "void";
            /**
             * Format: date
             * @example 2026-02-15
             */
            issuedAt: string;
        };
        Payment: {
            /** @example pay_001 */
            id: string;
            /** @example prj_001 */
            projectId: string;
            /**
             * Format: double
             * @example 25000000
             */
            amount: number;
            /** @enum {string} */
            method: "transfer" | "cash" | "giro";
            /**
             * Format: date
             * @example 2026-02-18
             */
            paidAt: string;
            /** @example BANK-TRX-12345 */
            reference?: string;
        };
        ProgressPhoto: {
            /**
             * Format: uri
             * @example https://cdn.example.com/progress/1.jpg
             */
            url: string;
            /** @example Pondasi selesai */
            caption?: string;
        };
        ProgressReport: {
            /** @example prg_001 */
            id: string;
            /** @example prj_001 */
            projectId: string;
            /** @example 3 */
            weekNumber: number;
            /** @example Pekerjaan struktur 40%. */
            notes: string;
            photos: components["schemas"]["ProgressPhoto"][];
            /** @enum {string} */
            qcStatus: "pending" | "approved" | "rejected";
        };
        Client: {
            /** @example cli_001 */
            id: string;
            /** @example PT Sinar Abadi */
            name: string;
            /**
             * Format: email
             * @example admin@sinarabadi.co.id
             */
            contactEmail?: string;
        };
        Supplier: {
            /** @example sup_001 */
            id: string;
            /** @example CV Maju Jaya */
            name: string;
            /**
             * Format: email
             * @example sales@majujaya.co.id
             */
            contactEmail?: string;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Authentication required."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "One or more fields are invalid.",
                 *         "details": [
                 *           {
                 *             "field": "name",
                 *             "issue": "Required"
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "Resource not found."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
